# Generated by Django 6.0.3 on 2026-09-29 07:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('transaction_reference', models.CharField(editable=False, max_length=32, unique=True)),
                ('provider_transaction_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_PROCESSING', 'Payment processing'), ('PAYMENT_RECEIVED', 'Payment received'), ('PAYMENT_FAILED', 'Payment failed'), ('PAYMENT_CANCELLED', 'Payment cancelled')], default='PAYMENT_PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payments', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer_payments', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='earnings',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning', to='users.payment'),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(max_length=3)),
                ('destination_country', models.CharField(max_length=2)),
                ('destination_currency', models.CharField(max_length=3)),
                ('payout_method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile money'), ('BANK_TRANSFER', 'Bank transfer')], max_length=32)),
                ('destination_reference', models.CharField(blank=True, max_length=100)),
                ('transaction_reference', models.CharField(editable=False, max_length=40, unique=True)),
                ('provider_transaction_reference', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('PAYOUT_PENDING', 'Payout pending'), ('PAYOUT_PROCESSING', 'Payout processing'), ('PAYOUT_PAID', 'Payout paid'), ('PAYOUT_FAILED', 'Payout failed'), ('PAYOUT_CANCELLED', 'Payout cancelled')], default='PAYOUT_PENDING', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='users.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='earnings',
            name='payout',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning', to='users.payout'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PAYMENT_PENDING', 'PAYMENT_PROCESSING', 'PAYMENT_RECEIVED'])), fields=('job',), name='unique_active_payment_per_job'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PAYOUT_PENDING', 'PAYOUT_PROCESSING', 'PAYOUT_PAID'])), fields=('payment',), name='unique_active_payout_per_payment'),
        ),
    ]
